title: sjmz

author: serghej mazza
email: serghejm@gmail.com

linkedin_username: serghej-mazza-b220a121b
linkedin_desc: Serghej Mazza on Linkedin
instagram_username: setteluglioband
instagram_desc: My band

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

